/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Aadhya.glb --transform 
Files: Aadhya.glb [28.07MB] > /Users/jashwanthsupercode/superCode projects/aadyah/public/Aadhya-transformed.glb [263.18KB] (99%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Aadhya-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={56.106} scale={5.287} />
      <mesh geometry={nodes.Earth_.geometry} material={materials['Material.001']} position={[0.234, 0.25, -42.94]} rotation={[0.389, -0.245, 3.054]} scale={-12.921} />
      <mesh geometry={nodes.Moon.geometry} material={materials['Material.002']} position={[33.679, 17.157, -51.773]} rotation={[1.205, 0.203, 0.067]} scale={-1.763} />
      <mesh geometry={nodes.Mars.geometry} material={materials['Material.003']} position={[-34.067, 1.245, 56.371]} rotation={[-0.016, -1.146, -0.306]} scale={-6.037} />
    </group>
  )
}

useGLTF.preload('/Aadhya-transformed.glb')
