/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Aadhya_final.glb --transform 
Files: Aadhya_final.glb [28.05MB] > /Users/jashwanthsupercode/superCode projects/aadyah/public/Aadhya_final-transformed.glb [274.92KB] (99%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Aadhya_final-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={56.106} scale={5.287} />
        <mesh name="Earth_" geometry={nodes.Earth_.geometry} material={materials['Material.001']} position={[0.234, 0.25, -42.94]} rotation={[0.389, -0.245, 3.054]} scale={-12.921} />
        <mesh name="Moon" geometry={nodes.Moon.geometry} material={materials['Material.002']} position={[33.679, 17.157, -51.773]} scale={0} />
        <mesh name="Mars" geometry={nodes.Mars.geometry} material={materials['Material.003']} position={[-34.067, 1.245, 56.371]} rotation={[-0.016, -1.146, -0.306]} scale={-6.037} />
      </group>
    </group>
  )
}

useGLTF.preload('/Aadhya_final-transformed.glb')
