/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 supercode_1.glb --transform 
Files: supercode_1.glb [345.01KB] > /Users/jashwanthsupercode/superCode projects/aadyah/public/supercode_1-transformed.glb [69.16KB] (80%)
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

export function ModelTest(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/supercode_1-transformed.glb"
  );
  console.log("nodes: ", nodes);
  console.log("animations: ", animations);
  console.log("materials: ", materials);
  const { actions } = useAnimations(animations, group);
  console.log("actions: ", actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty002" position={[-9.677, -0.908, 0.04]} scale={0} />
        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={1000}
          near={0.001}
          fov={22.895}
          position={[-0.083, 0.016, 0]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Sphere001"
          geometry={nodes.Sphere001.geometry}
          material={nodes.Sphere001.material}
          position={[-8.671, 0.541, 0.007]}
          rotation={[-Math.PI, -0.082, -Math.PI]}
          scale={0.039}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/supercode_1-transformed.glb");
