/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 supercode_01.glb --transform 
Files: supercode_01.glb [41.15MB] > /Users/jashwanthsupercode/superCode projects/aadyah/public/supercode_01-transformed.glb [563.77KB] (99%)
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

export function Model22(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/supercode_01.glb");
  console.log("animations: ", animations);
  console.log("nodes: ", nodes);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={1000}
          near={0.001}
          fov={22.895}
          position={[-0.083, 0.016, 0]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Earth001"
          geometry={nodes.Earth001.geometry}
          material={nodes.Earth001.material}
          position={[-7.545, 0, 0]}
          scale={1.079}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/supercode_01.glb");
